### ISSUE TITLE
Can't remove candle lighting

### ISSUE THREAD

**Issue by DovieW** [hebcal/hebcal-rest-api#281]
Hi, I can't seem to create a request that removes candle lighting.
Here's the request I'm using
https://www.hebcal.com/hebcal?v=1&cfg=json&maj=on&min=on&mod=off&nx=on&year=now&month=x&ss=on&mf=on&c=off&geo=zip&s=off&zip=10977&D=off&d=off&o=off&F=off&myomi=off

**Comment by mjradwin** [comment]
Specifying a geographic parameter (such as `zip=`) implies `c=on`. Try removing the ZIP code and candle lighting times should go away?

**Comment by DovieW** [comment]
Oh right, thank you
